SCMOD-9609: Adding elasticsearch credentials
CAFAudit/audit-service pull request #107
Opened 2020-07-24 14:01 UTC by rorytorneymf

Jira: https://portal.digitalsafe.net/browse/SCMOD-9609

2020-07-24 14:04 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFAudit&REPO_NAME=audit-service&BRANCH_NAME=SCMOD-9609) to go ahead and create the build...

2020-07-24 14:06 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFAudit/job/CAFAudit~audit-service~SCMOD-9609~CI

2020-07-24 14:45 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/CAFAudit_CI_audit-service_SCMOD-9609

2020-07-27 16:13 UTC, dermot-hardy requested changes

2020-07-27 16:13 UTC, dermot-hardy commented on caf-audit-monkey/README.md
> +    <td>ElasticSearch username. Defaults to null (anonymous access).</td>
Elasticsearch is one word.

```suggestion
    <td>Elasticsearch username. Defaults to null (anonymous access).</td>
```

2020-07-27 16:13 UTC, dermot-hardy commented on caf-audit-monkey/README.md
> +    <td>ElasticSearch password. Defaults to null (anonymous access).</td>
```suggestion
    <td>Elasticsearch password. Defaults to null (anonymous access).</td>
```

2020-07-27 16:13 UTC, dermot-hardy commented on caf-audit/README.md
> +- `CAF_ELASTIC_USERNAME`: ElasticSearch username. Defaults to null (anonymous access).
```suggestion
- `CAF_ELASTIC_USERNAME`: Elasticsearch username. Defaults to null (anonymous access).
```

2020-07-27 16:13 UTC, dermot-hardy commented on caf-audit/README.md
> +- `CAF_ELASTIC_PASSWORD`: ElasticSearch password. Defaults to null (anonymous access).
```suggestion
- `CAF_ELASTIC_PASSWORD`: Elasticsearch password. Defaults to null (anonymous access).
```

2020-07-27 16:13 UTC, dermot-hardy commented on caf-audit-binding-elasticsearch/src/main/java/com/hpe/caf/auditing/elastic/ElasticAuditRestHighLevelClientFactory.java
> +     * @param elasticPassword comma ElasticSearch password
```suggestion
     * @param elasticUsername Elasticsearch username
     * @param elasticPassword Elasticsearch password
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources/production-marathon/README.md
> +- `CAF_ELASTIC_PASSWORD`: ElasticSearch password. Defaults to null (anonymous access).
```suggestion
- `CAF_ELASTIC_USERNAME`: Elasticsearch username. Defaults to null (anonymous access).

- `CAF_ELASTIC_PASSWORD`: Elasticsearch password. Defaults to null (anonymous access).
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources/production-marathon/environment.sh
> +# ElasticSearch password.
```suggestion
# Elasticsearch username.
export CAF_ELASTIC_USERNAME=

# Elasticsearch password.
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources/production-marathon/production-prereqs/README.md
> +- `CAF_ELASTIC_PASSWORD`: ElasticSearch password. Defaults to null (anonymous access).
```suggestion
- `CAF_ELASTIC_USERNAME`: Elasticsearch username. Defaults to null (anonymous access).

- `CAF_ELASTIC_PASSWORD`: Elasticsearch password. Defaults to null (anonymous access).
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources/production-swarm/README.md
> +	## ElasticSearch password.
```suggestion
	## Elasticsearch username.
	export CAF_ELASTIC_USERNAME=
	## Elasticsearch password.
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources/production-swarm/environment.sh
> +## ElasticSearch password.
```suggestion
## Elasticsearch username.
export CAF_ELASTIC_USERNAME=
## Elasticsearch password.
```

2020-07-27 16:13 UTC, dermot-hardy commented on deploy/src/main/resources-filtered/production-marathon/marathon.json.b
> +            "CAF_LOG_LEVEL": "INFO",
Are you allowed trailing commas?  There's no reason to change this line anyway.

```suggestion
            "CAF_LOG_LEVEL": "INFO"            
```

2020-07-27 16:13 UTC, dermot-hardy commented on docs/pages/en-us/Client-API.md
> +- `CAF_ELASTIC_PASSWORD`: ElasticSearch password. Defaults to null (anonymous access).
```suggestion
- `CAF_ELASTIC_USERNAME`: Elasticsearch username. Defaults to null (anonymous access).
- `CAF_ELASTIC_PASSWORD`: Elasticsearch password. Defaults to null (anonymous access).
```

2020-07-27 16:13 UTC, dermot-hardy commented on docs/pages/en-us/Getting-Started.md
> +        - `CAF_ELASTIC_PASSWORD`: ElasticSearch password. Defaults to null (anonymous access).
```suggestion
        - `CAF_ELASTIC_USERNAME`: Elasticsearch username. Defaults to null (anonymous access).
        - `CAF_ELASTIC_PASSWORD`: Elasticsearch password. Defaults to null (anonymous access).
```

2020-07-28 10:34 UTC, andyreidz commented
@dermot-hardy The suggested changes feature is nice. 
Shame that multiple changes to a single file can't be batched and applying a change forces a page reload. It makes applying the changes take much longer and also collapses the hidden conversations each time.

2020-07-28 11:50 UTC, dermot-hardy approved these changes
If you really wanted to you could do another PR into this one for that.

2020-07-28 11:54 UTC, merged