CAF-2380: Getting started guide documentation re-write for Audit 3.0.0 release
CAFAudit/audit-service pull request #14
Opened 2017-05-08 14:00 UTC by CJComac

2017-05-08 15:19 UTC, glucy requested changes
Further reviewing required once a developer build has been created.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +1. Using Audit Service Deployment, launch an Elasticsearch cluster.
Use the [Audit Service Deploy Project](https://github.com/CAFAudit/audit-service-deploy), to launch an Elasticsearch cluster.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +For more information on Audit Service Deployment, go [here](https://github.com/CAFAudit/audit-service-deploy).
For more information on Audit Service Deploy, go [here](https://github.com/CAFAudit/audit-service-deploy).

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +For developer deployment of Elasticsearch, please follow the Audit Service Deployment documentation as it covers configuring and starting of Elasticsearch cluster in Docker. For more information on A
For a developer deployment of Elasticsearch, please follow the Audit Service Deployment documentation.  The documentation covers configuring and starting of an Elasticsearch cluster in Docker.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
>  Many IDEs and XML editors use the schema file to provide IntelliSense and type-ahead when authoring the definition file.
Many IDEs and XML editors use the schema file to provide IntelliSense / Auto-Complete when authoring the definition file.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +As previously mentioned, in order to use Auditing, you must first define the audit events in an audit event definition file. After you create the definition file, you use it to generate a client-side
library directed should be "library directly, [here](Client-API)."

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +This object represents a logical connection to persistent storage (that is, Elasticsearch in the current implementation). It is a thread-safe object. ***Please take into account that this object requ
This object represents a logical connection to persistent storage  
Update to:  
This object represents a logical connection to the datastore

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +	    "hostAndPort": "<Elasticsearch_Cluser_Node_1>:<Port_Number>,<Elasticsearch_Cluser_Node_2>:<Port_Number>",
Side note:

The parameter hostAndPort is going to change to "hostAndPortValues".

This change will hopefully be made tomorrow, so feel free to update the documentation in advance.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +- `hostAndPort` refers to one or more of the nodes of the Elasticsearch cluster as a comma-separated list.
hostAndPort to become hostAndPortValues

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +This object represents a logical channel to the persistent storage (that is, Elasticsearch in this implementation). **It is NOT a thread-safe object and must not be shared across threads without sync
persistent storage --> datastore

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
>  The `AuditChannel` object can be constructed using the `createChannel()` method on the `AuditConnectionn` object. It does not take any parameters.
Typo: `AuditConnectionn` should be `AuditConnection`

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +The method will throw an exception if the audit event could not be stored for some reason (for example, network failure or supplying unsupported tenantId characters).
Are we now offering some form of validation on the tenantId?  If so great, if not we shouldn't suggest that we are in the document.

2017-05-08 15:19 UTC, glucy commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit` whose `userId` is `JoanneBloggs@yourcompany.com`:
Is Joe on his holidays?  :-P

2017-05-08 15:27 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +The method will throw an exception if the audit event could not be stored for some reason (for example, network failure or supplying unsupported tenantId characters).
We currently throw an illegal argument exception if you try to pass commas within the tenantId

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit` whose `userId` is `JoanneBloggs@yourcompany.com`:
Joanne might be able to answer that :)

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
>  The `AuditChannel` object can be constructed using the `createChannel()` method on the `AuditConnectionn` object. It does not take any parameters.
Corrected in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +This object represents a logical channel to the persistent storage (that is, Elasticsearch in this implementation). **It is NOT a thread-safe object and must not be shared across threads without sync
Adjusted in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +- `hostAndPort` refers to one or more of the nodes of the Elasticsearch cluster as a comma-separated list.
Adjusted in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +	    "hostAndPort": "<Elasticsearch_Cluser_Node_1>:<Port_Number>,<Elasticsearch_Cluser_Node_2>:<Port_Number>",
Adjusted in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +This object represents a logical connection to persistent storage (that is, Elasticsearch in the current implementation). It is a thread-safe object. ***Please take into account that this object requ
Adjusted in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +This object represents a logical connection to persistent storage (that is, Elasticsearch in the current implementation). It is a thread-safe object. ***Please take into account that this object requ
Adjusted in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +As previously mentioned, in order to use Auditing, you must first define the audit events in an audit event definition file. After you create the definition file, you use it to generate a client-side
Corrected in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
>  Many IDEs and XML editors use the schema file to provide IntelliSense and type-ahead when authoring the definition file.
Changed in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +For developer deployment of Elasticsearch, please follow the Audit Service Deployment documentation as it covers configuring and starting of Elasticsearch cluster in Docker. For more information on A
Changed in the latest commit

2017-05-08 15:55 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +For more information on Audit Service Deployment, go [here](https://github.com/CAFAudit/audit-service-deploy).
Changed in the latest commit

2017-05-08 15:56 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +1. Using Audit Service Deployment, launch an Elasticsearch cluster.
Changed in the latest commit

2017-05-09 08:07 UTC, mulhollandc requested changes
Final comment would be have you tested the actual code snippets that you are including on this page to make sure that when it is all brought together that an audit event message is successfully sent and indexed into Elasticsearch?

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
> +Given this configuration, you would configure Auditing by creating a file named `cfg_sampleappgroup_sampleapp_ElasticsearchAuditConfiguration` in the `/etc/sampleapp/config/` directory. The contents
I don't think this is correct. The configuration file I think needs to match the configuration class name, which in this case is actually ElasticAuditConfiguration.

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
> +	    "hostAndPortValues": "<Elasticsearch_Cluser_Node_1>:<Port_Number>,<Elasticsearch_Cluser_Node_2>:<Port_Number>",
Just to note that hostAndPortValues probably won;t work right now. caf-audit currently expects hostAndPort.

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
> +- `hostAndPortValues` refers to one or more of the nodes of the Elasticsearch cluster as a comma-separated list.
Same as above for hostAndPortValues.

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
>  After you successfully construct an `AuditConnection` object, you must construct an `AuditChannel` object.
I'd re-word to "After you successfully construct an `AuditConnection` object, you must then create ..."

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit`:
Explain how you got the results. Just a URL in the browser? If so, what format is expected?

2017-05-09 08:07 UTC, mulhollandc commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit` whose `userId` is `JoanneBloggs@yourcompany.com`:
Same comment as above for other figure.

2017-05-09 09:54 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +	    "hostAndPortValues": "<Elasticsearch_Cluser_Node_1>:<Port_Number>,<Elasticsearch_Cluser_Node_2>:<Port_Number>",
3.0.0 will be released as hostAndPortValues. Given the current snapshot, during my manual test I will need to change this

2017-05-09 09:54 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +- `hostAndPortValues` refers to one or more of the nodes of the Elasticsearch cluster as a comma-separated list.
3.0.0 will be released as hostAndPortValues. Given the current snapshot, during my manual test I will need to change this

2017-05-09 10:36 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit` whose `userId` is `JoanneBloggs@yourcompany.com`:
In the latest commit, reworded to:
"The following Search API operation, `http://<Elasticsearch_Cluser_Node_1>:<Port_Number>/00000001_audit/cafAuditEvent/_search?q=userId:JoanneBloggs@yourcompany.com`, can be run to display the audit event entries belonging to tenantId `00000001` and whose `userId` is `JoanneBloggs@yourcompany.com`:"

2017-05-09 10:36 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +The following figure shows all audit event entries belonging to tenant index `00000001_audit`:
In the latest commit, reworded to:
"Every time an `AuditLog` method is called, a new application audit event is entered into the tenant's index. 

Elasticsearch offers a RESTful interface for querying index entries. For more information on the Elasticsearch REST Search API, go [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html).

Using the configuration source details above, the following Search API operation, `http://<Elasticsearch_Cluser_Node_1>:<Port_Number>/00000001_audit/cafAuditEvent/_search`, can be run to display all audit event entries belonging to tenantId `00000001`:"

2017-05-09 10:36 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
>  After you successfully construct an `AuditConnection` object, you must construct an `AuditChannel` object.
Adjusted in the latest commit

2017-05-09 10:36 UTC, CJComac commented on docs/pages/en-us/Getting-Started.md
> +Given this configuration, you would configure Auditing by creating a file named `cfg_sampleappgroup_sampleapp_ElasticsearchAuditConfiguration` in the `/etc/sampleapp/config/` directory. The contents
Adjusted in the latest commit

2017-05-09 14:35 UTC, mulhollandc approved these changes

2017-05-09 14:59 UTC, glucy approved these changes

2017-05-09 16:00 UTC, merged