CAF-2693: Add support for Elasticsearch string types (i.e. keyword and text)
CAFAudit/audit-service pull request #21
Opened 2017-05-15 10:09 UTC by mulhollandc

Can the audit-service changes for ES string type support be reviewed please?
A new 'IndexingHint' option has been added to both audit schema and web service contract to allow the end user to specify an optional indexing hint for audit event parameters of type 'string'. fulltext will map onto ES 'TEXT' while keyword maps on ES 'KEYWORD' string types.

2017-05-16 11:16 UTC, dermot-hardy requested changes

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-maven-plugin/caf-audit-maven-plugin.md
> +		  <IndexingHint>fulltext</IndexingHint>
Tabs used instead of spaces.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-schema/README.md
> +                <Description>Document Identifier</Description>
Why are these lines changing?  Whitespace seems screwed up in this file.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-schema/README.md
> +A list of parameter elements are then defined for each Audit Event. This includes the `Name` of the parameter, the `Type` (i.e. string, short, int, long, float, double, boolean or date) and the `Desc
I don't understand from this why or when I might use the `fulltext` or `keyword` hint.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-schema/src/main/resources/schema/AuditedApplication.xsd
> +      <element name="IndexingHint" type="aa:AuditEventParamIndexingHint" minOccurs="0"/>
Rogue whitespace at the end of this line (and some more in line 90).

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-service-contract/src/main/resources/com/hpe/caf/services/audit/contract/swagger.yaml
> +        default: keyword
There is nothing in the schema about making keyword a default, so it shouldn't be made a default here.  It is really up to the implementation what the default is.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-service/src/main/java/com/hpe/caf/services/audit/server/api/impl/AuditeventsApiServiceImpl.java
> +import com.hpe.caf.auditing.*;
Don't prefer star imports.  It is better to individually list out the classes required.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-service/src/main/java/com/hpe/caf/services/audit/server/api/impl/AuditeventsApiServiceImpl.java
> +                //  Add event paramter details to the audit event builder object by type.
This is the opposite of a spelling correction.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-service/src/main/java/com/hpe/caf/services/audit/server/api/impl/AuditeventsApiServiceImpl.java
> +    private void addCustomFieldsToAuditEventMessage(AuditEventBuilder auditEventBuilder, final NewAuditEvent newAuditEvent) throws Exception, BadRequestException {
Why do we now need to accept all Exceptions?

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit-service/src/main/java/com/hpe/caf/services/audit/server/api/impl/AuditeventsApiServiceImpl.java
> +                                    //  Nothing to do here.
Since this default branch should never be hit you should be throwing a `RuntimeException` in it.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditEventBuilder.java
> +    ) throws Exception;
- Why does this method throw an Exception when none of the other `addEventParameter()` methods do?
- The parameters should be aligned the same as the other methods in the module.
- I think a default implementation which calls `addEventParameter()` would be OK (as it is just a hint).

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditEventBuilder.java
> +            int maxLength
Parameters not aligned like the other methods.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditIndexingHint.java
> +}
Source files should always end with a newline.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/elastic/ElasticAuditEventBuilder.java
> +                throw new Exception(errorMessage);
This shouldn't be a checked exception.  Consider an `IllegalArgumentException` or else just use a `RuntimeException`.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/test/java/com/hpe/caf/auditing/elastic/ElasticAuditIT.java
> +                if (indexingHint == AuditIndexingHint.KEYWORD) {
Can `indexingHint` be `null`?

2017-05-16 11:16 UTC, dermot-hardy commented on docs/pages/en-us/Getting-Started.md
> +			  <IndexingHint>keyword</IndexingHint>
Whitespace looks screwed up.

2017-05-16 11:16 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/elastic/ElasticAuditEventBuilder.java
> +        switch (indexingHint) {
If `indexingHint` is `null` this will cause a `NullReferenceException`.  A `null` indexing hint should mean no hint, and just do the same as the overload that doesn't take a hint.

2017-05-16 15:57 UTC, mulhollandc commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditEventBuilder.java
> +    ) throws Exception;
@dermot-hardy Sorry to ask but can you explain the last point please about the default implementation? I'm not sure what you mean exactly.

2017-05-16 16:05 UTC, mulhollandc commented on caf-audit/src/test/java/com/hpe/caf/auditing/elastic/ElasticAuditIT.java
> +                if (indexingHint == AuditIndexingHint.KEYWORD) {
Not in this case since we are dealing with string type fields. We always pass an indexing hint when verifying search results for fields of this type.

2017-05-16 16:35 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditEventBuilder.java
> +    ) throws Exception;
Let's provide a default implementation which ignores the indexing hint, so that the interface change is not a breaking change.

2017-05-16 16:38 UTC, dermot-hardy commented on caf-audit/src/test/java/com/hpe/caf/auditing/elastic/ElasticAuditIT.java
> +                if (indexingHint == AuditIndexingHint.KEYWORD) {
I think it should be checked anyway - if you're sure it's impossible then throw a `RuntimeException`.

2017-05-17 11:35 UTC, mulhollandc commented
@dermot-hardy I have addressed all of your code review comments.

2017-05-17 14:15 UTC, dermot-hardy approved these changes

2017-05-17 14:57 UTC, merged