CAF-2870: CAF Audit Maven plugin generate AuditLog as test resource option
CAFAudit/audit-service pull request #26
Opened 2017-05-18 14:18 UTC by CJComac

2017-05-18 14:54 UTC, mulhollandc requested changes

2017-05-18 14:54 UTC, mulhollandc commented on caf-audit-maven-plugin/src/main/java/com/hpe/caf/auditing/plugins/XMLToJavaMojo.java
> +            // If generateAsTestResource has been set to true, set the output directory to be test resource directory
Missing full stop.

2017-05-18 14:54 UTC, mulhollandc commented on caf-audit-service-container/pom.xml
> +            <artifactId>caf-audit-service-testing-audit</artifactId>
I would re-name this artifact as it has 'audit' twice in it. Maybe drop '-audit' from the end.

2017-05-18 14:54 UTC, mulhollandc commented on caf-audit-service-testing-audit/pom.xml
> +    <artifactId>caf-audit-service-testing-audit</artifactId>
Rename. Also include a README for this new project.

2017-05-18 14:54 UTC, mulhollandc commented on pom.xml
> +        <module>caf-audit-service-testing-audit</module>
Rename.

2017-05-18 14:54 UTC, mulhollandc commented on caf-audit/test-case/tenant1Events.yaml
> -numberOfMessages: 10
Why have these yml files been removed?

2017-05-18 14:54 UTC, mulhollandc commented on caf-audit-maven-plugin/src/main/java/com/hpe/caf/auditing/plugins/XMLToJavaMojo.java
> +    @Parameter(property = "generateAsTestResource", defaultValue = "false")
Check with Dermot if this new parameter needs documented under audit plugin sections of caf-audit README, Getting Started and Client-Side API pages.

2017-05-18 17:07 UTC, CJComac commented on caf-audit/test-case/tenant1Events.yaml
> -numberOfMessages: 10
Not used or needed

2017-05-18 17:10 UTC, CJComac commented on caf-audit-maven-plugin/src/main/java/com/hpe/caf/auditing/plugins/XMLToJavaMojo.java
> +    @Parameter(property = "generateAsTestResource", defaultValue = "false")
Asked Dermot and we agreed that this option doesn't need documented. It would be of no use to anyone other than ourselves.

2017-05-19 10:16 UTC, CJComac reviewed
Connor's feedback changes made and committed to the branch

2017-05-19 10:16 UTC, CJComac commented on caf-audit-maven-plugin/src/main/java/com/hpe/caf/auditing/plugins/XMLToJavaMojo.java
> +            // If generateAsTestResource has been set to true, set the output directory to be test resource directory
Corrected in the latest commit

2017-05-19 10:16 UTC, CJComac commented on caf-audit-service-container/pom.xml
> +            <artifactId>caf-audit-service-testing-audit</artifactId>
I have renamed this to "-auditlog" in the latest commit. Changing it to caf-audit-service-testing sounds like it contains tests for the audit service.

2017-05-19 10:16 UTC, CJComac commented on caf-audit-service-testing-audit/pom.xml
> +    <artifactId>caf-audit-service-testing-audit</artifactId>
Included README in the latest commit

2017-05-19 10:16 UTC, CJComac commented on pom.xml
> +        <module>caf-audit-service-testing-audit</module>
I have renamed this to "-auditlog" in the latest commit. Changing it to caf-audit-service-testing sounds like it contains tests for the audit service.

2017-05-19 10:20 UTC, mulhollandc approved these changes

2017-05-19 10:27 UTC, merged