Caf-2846: Environment Variable
CAFAudit/audit-service pull request #27
Opened 2017-05-18 14:32 UTC by arogan92

2017-05-18 15:00 UTC, mulhollandc requested changes

2017-05-18 15:00 UTC, mulhollandc commented on caf-audit-service-container/README.md
> -The path to the directory containing the config.properties which can be used as an alternative means of specifying the environment variables. e.g. .\config-props
This section should begin with CAF_LOG_LEVEL with a paragraph or set of paragraphs directly under (just like the other settings).

Does audit-service-deploy README not require a similar change?

2017-05-18 15:00 UTC, mulhollandc commented on caf-audit-service/src/main/resources/log4j2.xml
> +                <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
Is this the same pattern used in other services. e.g. document-id and job-service? Maybe it doesn't matter - just a thought.

2017-05-18 15:03 UTC, arogan92 commented on caf-audit-service-container/README.md
> -The path to the directory containing the config.properties which can be used as an alternative means of specifying the environment variables. e.g. .\config-props
Readme for audit-service-deploy is in a separate pull request. (https://github.com/CAFAudit/audit-service-deploy/pull/5)

I'll update this readme and push the changes

2017-05-18 15:15 UTC, arogan92 commented
Readme updated after comments from Connor

2017-05-18 15:23 UTC, arogan92 commented on caf-audit-service/src/main/resources/log4j2.xml
> +                <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
The others contain a package and status in the configuration header. Sitting with Andy this morning its apparent that we don't really need that.

I don't think we require to separate the Logging levels amongst different packages either? Like that of Document-id?

2017-05-19 08:22 UTC, mulhollandc commented on caf-audit-service/src/main/resources/log4j2.xml
> +                <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
Sorry but I wasn't referring to separate logging levels etc. I meant the actual PatternLayout format you have specified.

2017-05-19 08:36 UTC, mulhollandc requested changes

2017-05-19 08:36 UTC, mulhollandc commented on caf-audit-service-container/README.md
> +##### CAF\_LOG\_LEVEL
Change section to:

##### CAF\_LOG\_LEVEL

The logging level for the CAF Audit Web Service. e.g debug

Logging levels supported include:

* warn
* error
* info
* trace
* debug
* all

A default logging level of **info** is applied if this environment variable is not configured.

2017-05-19 10:01 UTC, arogan92 commented on caf-audit-service/src/main/resources/log4j2.xml
> +                <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
Yep, the pattern layout is identical to that of documentid-service

2017-05-19 10:14 UTC, arogan92 commented
Changes made to README's and code-formatting in log4j.xml files after pull request comments

2017-05-19 10:16 UTC, mulhollandc requested changes

2017-05-19 10:16 UTC, mulhollandc commented on caf-audit-service-container/README.md
> +Logging levels support include:
Should this be 'Logging levels supported include:' or 'The logging levels supported are:'? The line was to indicate which suitable logging levels are supported through the configuration.

2017-05-19 10:19 UTC, arogan92 commented on caf-audit-service-container/README.md
> +Logging levels support include:
You're right. Grammar error

2017-05-19 10:22 UTC, mulhollandc approved these changes

2017-05-19 10:23 UTC, arogan92 commented
Grammar error has been fixed

2017-05-19 10:29 UTC, arogan92 commented
Release notes updated

2017-05-19 10:32 UTC, mulhollandc requested changes

2017-05-19 10:32 UTC, mulhollandc commented on release-notes-3.1.0.md
> +- [CAF-2846](https://jira.autonomy.com/browse/CAF-2846): Added support for configuring the Audit Web Service logging levels through an environment variable
Adam I think this should be changed to Audit Service and not specific to the Web service as you have added this to the client side code as well if I recall?

2017-05-19 10:41 UTC, arogan92 commented on release-notes-3.1.0.md
> +- [CAF-2846](https://jira.autonomy.com/browse/CAF-2846): Added support for configuring the Audit Web Service logging levels through an environment variable
done

2017-05-19 10:51 UTC, mulhollandc approved these changes

2017-05-19 10:51 UTC, merged