CAF-3517 Update copyright statements to EntIT and added updated organisat…
CAFAudit/audit-service pull request #42
Opened 2017-09-29 16:25 UTC by michael-bryson

…ion section to the pom file

2017-09-30 14:30 UTC, dermot-hardy requested changes

2017-09-30 14:30 UTC, dermot-hardy commented on caf-audit-maven-plugin/src/test/resources/transform/AuditLog.java
> + * Copyright 2015-2017 EntIT Software LLC, a Micro Focus company.
This file doesn't look right.

2017-10-02 08:14 UTC, michael-bryson commented
Looks like something went wrong with the mvn license format command where instead of replacing headers it is adding a new one. Will review this now.

2017-10-02 08:58 UTC, michael-bryson commented
It seems that this issue occurred on any files where the license header was not at the start of the file. I have removed all duplicates now.

2017-10-03 11:16 UTC, dermot-hardy approved these changes

2017-10-03 11:16 UTC, merged