SCMOD-5876: Updated to remove configuration source requirement
CAFAudit/audit-service pull request #52
Opened 2019-02-25 11:07 UTC by Anthony-McGreevy

2019-02-25 11:08 UTC, Anthony-McGreevy commented
@davidegph im still reading through the documentation for this project to make sure I haven't missed anything, but in the meantime, if you get time can you review the code changes.

2019-02-25 11:09 UTC, Anthony-McGreevy commented
Dev Build: http://sou-jenkins2.hpeswlab.net/job/CAFAudit/view/Developer/job/CAFAudit~audit-service~SCMOD-5876~CI/

2019-02-25 17:45 UTC, davidegph commented
Shouldn't this env changed?
https://github.com/CAFAudit/audit-service/blob/c4a582c0a17dc0a67d46f0c335813a681b010cb3/caf-audit-service-container/pom.xml#L191
and also shards and replicas added?

2019-02-25 17:54 UTC, davidegph commented
@Anthony-McGreevy See my comment above, all the rest is fine. Once you will reply me, I will approve this PR.

2019-02-26 14:49 UTC, davidegph approved these changes

2019-02-26 14:52 UTC, Anthony-McGreevy commented
> Shouldn't this env changed?
> [audit-service/caf-audit-service-container/pom.xml](https://github.com/CAFAudit/audit-service/blob/c4a582c0a17dc0a67d46f0c335813a681b010cb3/caf-audit-service-container/pom.xml#L191)
> 
> Line 191 in [c4a582c](/CAFAudit/audit-service/commit/c4a582c0a17dc0a67d46f0c335813a681b010cb3)
> 
>  <CAF_ELASTIC_HOST_AND_PORT>${docker.host.address}:${elasticsearch.transport.port}</CAF_ELASTIC_HOST_AND_PORT> 
> 
> and also shards and replicas added?

This is just configuration for tests so the name is fine. Also, the tests don't need the configuration for the shards and replicas.

2019-02-27 00:10 UTC, dermot-hardy requested changes

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit-service-container/pom.xml
>                          <CAF_APPNAME>test/auditservice</CAF_APPNAME>
Is `CAF_APPNAME` not a part of CAF Configuration?

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit-service-container/pom.xml
> +                                            </dependencySet>
What is this change about?

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit-service-container/pom.xml
> +                                    <port>1701:5005</port>
Was this meant to be checked in?  If so it will randomly cause build failures because it's not using dynamic ports.

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit-elasticclient/src/main/java/com/hpe/caf/auditing/elastic/ElasticAuditConnectionProvider.java
>  import com.hpe.caf.api.ConfigurationException;
References to `com.hpe.caf.api.ConfigurationException` should be gone - that is the CAF Configuration Exception.  If you need your own then you'll have to introduce one.

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/AuditConnectionFactory.java
> +     * are malformed
I wouldn't mention environment variables here, unless as an example - it is really up to the implementation where it gets its configuration from.

2019-02-27 00:10 UTC, dermot-hardy commented on caf-audit/README.md
> +- *CAF_ELASTIC_HOST_AND_PORT_VALUES*: A comma separated list of hostnames and ports to use when contacting elasticsearch. eg. localhost:9200,otherHost:9200
Use code format (i.e. backticks) rather than italics for the environment variables.  I wonder would they be better in a table?

2019-02-27 00:10 UTC, dermot-hardy commented on docs/pages/en-us/Getting-Started.md
> +Or the following environment variable when using with the webservice audit implementation:
Indenting doesn't look right.  WS config should not be subordinate to ES config.

2019-03-05 21:59 UTC, Anthony-McGreevy commented on caf-audit-service-container/pom.xml
> +                                            </dependencySet>
Previously none of the dependencies from this project were being built into the container, only the war for the service and the ui was built in. Now we need to build in the implementation jars and any dependencies they require at runtime, elasticsearch transport client for example.

2019-03-12 20:30 UTC, closed without merging