SCMOD-5877: Removed generic exception from interface
CAFAudit/audit-service pull request #60
Opened 2019-06-17 14:25 UTC by Anthony-McGreevy

2019-06-17 15:56 UTC, dermot-hardy requested changes
We will also need plugin changes but they can be a separate PR.

2019-06-17 15:56 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/exception/AuditFailureException.java
> +public class AuditFailureException extends Exception
How about `AuditingException`?  Having `Failure` in there seems redundant.

2019-06-17 15:56 UTC, dermot-hardy commented on caf-audit-binding-webservice/src/main/java/com/hpe/caf/auditing/webserviceclient/WebServiceClientAuditEventBuilder.java
> +            throw new AuditFailureException(errorMessage);
Is this not just library misuse?  If so then it should be some type of unchecked exception thrown here.

2019-06-17 15:56 UTC, dermot-hardy commented on caf-audit/src/main/java/com/hpe/caf/auditing/noop/NoopAuditEventBuilder.java
> +    public void send() throws IOException, AuditFailureException
You can actually drop the exception specification altogether here.

2019-06-19 10:10 UTC, Anthony-McGreevy commented
@dermot-hardy Can you look at this again. This now includes your requested changes and the changes required for the plugin.

2019-06-21 10:50 UTC, Anthony-McGreevy commented
@dermot-hardy  Can you try and look at this today if you have time.

2019-06-21 15:34 UTC, dermot-hardy approved these changes

2019-06-21 15:34 UTC, merged