[SCMOD-7628] Logging updates
CAFAudit/audit-service pull request #77
Opened 2019-10-05 00:27 UTC by kusumaghoshdastidar

Jira: https://portal.digitalsafe.net/browse/SCMOD-7628

Dev builds: http://sou-jenkins2.hpeswlab.net/job/CAFAudit/view/Developer/job/CAFAudit~audit-service~SCMOD-7628~CI/

2019-10-07 22:12 UTC, dermot-hardy requested changes

2019-10-07 22:12 UTC, dermot-hardy commented on caf-audit-binding-elasticsearch/src/test/java/com/hpe/caf/auditing/elastic/ElasticAuditIT.java
> +        System.setProperty("es.port", "9200");
Remove these lines.

2019-10-07 22:12 UTC, dermot-hardy commented on caf-audit-service-container/pom.xml
> +                                    <CAF_LOG_LEVEL>TRACE</CAF_LOG_LEVEL>
Does this really need to change?

2019-10-08 04:37 UTC, kusumaghoshdastidar commented on caf-audit-binding-elasticsearch/src/test/java/com/hpe/caf/auditing/elastic/ElasticAuditIT.java
> +        System.setProperty("es.port", "9200");
Removed

2019-10-08 04:38 UTC, kusumaghoshdastidar commented on caf-audit-service-container/pom.xml
> +                                    <CAF_LOG_LEVEL>TRACE</CAF_LOG_LEVEL>
No. Reverted

2019-10-08 18:24 UTC, dermot-hardy approved these changes
Did you get the log4j2 issue sorted out that you were showing me yesterday?

2019-10-08 18:27 UTC, kusumaghoshdastidar commented
> Did you get the log4j2 issue sorted out that you were showing me yesterday?

No.

2019-10-08 18:29 UTC, dermot-hardy commented
It should really be fixed as part of this PR.

2019-10-08 18:31 UTC, kusumaghoshdastidar commented
> It should really be fixed as part of this PR.

Ok

2019-10-11 22:37 UTC, merged